# ============================================================
# server.py — Central TLS/SSL Server
# ============================================================
# This is the heart of the system. It does 3 things:
#   1. Accepts secure (TLS) connections from Arduino clients
#   2. Authenticates each device using a secret token
#   3. Receives commands from the web UI and forwards them
#      to the correct Arduino client
# ============================================================

import socket        # For creating TCP network connections
import ssl           # For wrapping sockets with TLS encryption
import threading     # For handling multiple clients simultaneously
import json          # For encoding/decoding messages as JSON
import time          # For timestamps used in latency calculation

# ── Server Configuration ────────────────────────────────────
HOST = "0.0.0.0"       # Listen on ALL network interfaces
                        # (so both local and remote clients can connect)
PORT = 5000             # Port number the server listens on
AUTH_TOKEN = "MY_SECRET_KEY"  # Secret key — clients must send this to authenticate

# Paths to SSL certificate and private key
# These are generated by generate_cert.py
CERT_FILE = "server.crt"   # Public certificate (shared with clients)
KEY_FILE  = "server.key"   # Private key (kept secret on server only)

# ── Shared State ────────────────────────────────────────────
# Dictionary to store all connected and authenticated devices
# Key = device_id (e.g. "arduino1"), Value = SSL socket connection
clients = {}

# Lock to prevent race conditions when multiple threads
# read/write the clients dictionary at the same time
lock = threading.Lock()

# Flag to pause the terminal prompt when a client connects/disconnects
# so the output doesn't get mixed up
pause_print = False


# ============================================================
# handle_client() — Runs in a separate thread for each connection
# ============================================================
# Every time a new client connects, a new thread is spawned
# running this function. This allows multiple devices to be
# connected at the same time without blocking each other.
# ============================================================
def handle_client(conn, addr):

    global pause_print
    device_id = None   # Will be set after successful registration

    try:
        # ── Step 1: Receive the first message from the client ──
        # The first message tells us what type of connection this is:
        #   - "REGISTER" = an Arduino client trying to connect
        #   - "COMMAND"  = the web UI sending a command to forward
        data = conn.recv(4096).decode()
        msg = json.loads(data)

        # ── Handle Web UI Command ──────────────────────────────
        # The web UI doesn't register — it just sends a COMMAND
        # directly. The server finds the target device and
        # forwards the command to it.
        if msg["type"] == "COMMAND":
            device_id_target = msg["device_id"]

            with lock:   # Acquire lock before accessing clients dict
                if device_id_target in clients:
                    # Build the command message to forward
                    forward_msg = {
                        "type": "COMMAND",
                        "command": msg["command"],
                        "sent_time": msg["sent_time"]   # Keep original timestamp for latency calc
                    }
                    # Send the command to the Arduino client's socket
                    clients[device_id_target].send(json.dumps(forward_msg).encode())
                    print(f"[WEB COMMAND] Forwarded '{msg['command']}' to {device_id_target}")
                else:
                    # Device not found — it may not be connected yet
                    print(f"[WEB COMMAND] Device '{device_id_target}' not found")

            # Close the web UI's connection after forwarding
            # (web UI opens a fresh connection for each command)
            try:
                conn.shutdown(socket.SHUT_RDWR)   # Gracefully close both directions
            except OSError:
                pass   # Ignore if already closed
            conn.close()
            return   # Exit this thread — job done

        # ── Handle Arduino Client Registration ─────────────────
        # If the message type is not REGISTER, reject immediately
        if msg["type"] != "REGISTER":
            conn.close()
            return

        # Extract the device ID from the REGISTER message
        device_id = msg["device_id"]

        # ── Step 2: Authentication ─────────────────────────────
        # Send AUTH_REQUEST to ask the client for its secret token
        conn.send(b"AUTH_REQUEST")

        # Wait for the client to send back its token
        token = conn.recv(1024).decode()

        # Check if the token matches our secret key
        if token != AUTH_TOKEN:
            conn.send(b"AUTH_FAILED")   # Reject — wrong token
            conn.close()
            return

        # Token is correct — send AUTH_SUCCESS
        conn.send(b"AUTH_SUCCESS")

        # ── Step 3: Register the device ───────────────────────
        # Add this device to the clients dictionary so the server
        # can forward commands to it later
        with lock:
            clients[device_id] = conn

        print(f"[CONNECTED] {device_id} from {addr}")

        # ── Step 4: Listen for messages from this device ───────
        # Keep the connection alive and listen for incoming messages
        # (currently handles STATUS updates and ACK confirmations)
        while True:

            data = conn.recv(4096)

            # If recv() returns empty data, the client disconnected
            if not data:
                break

            message = json.loads(data.decode())

            # ── STATUS message ─────────────────────────────────
            # Device is reporting its system stats (CPU, memory, disk)
            # Not used by Arduino UNO but kept for future Raspberry Pi support
            if message["type"] == "STATUS":
                if not pause_print:
                    print(
                        f"[STATUS] {device_id} CPU:{message['cpu']} "
                        f"MEM:{message['memory']} DISK:{message['disk']}"
                    )

            # ── ACK message ────────────────────────────────────
            # Device has executed the command and is confirming it
            # Latency = current time - time when command was originally sent
            elif message["type"] == "ACK":
                latency = time.time() - message["sent_time"]
                print(
                    f"[ACK] {device_id} executed {message['command']} "
                    f"Latency: {latency:.4f} sec"
                )

    # ── Error Handling ─────────────────────────────────────────
    # Catch SSL errors and Windows-specific socket errors
    # WinError 10054 = connection forcibly closed by remote host (normal on Windows)
    # WinError 10053 = connection aborted by host machine (normal on Windows)
    except (ssl.SSLError, ConnectionAbortedError, ConnectionResetError, OSError) as e:
        if hasattr(e, 'winerror') and e.winerror in (10054, 10053):
            pass   # These are normal Windows disconnection codes — ignore them
        else:
            print("[ERROR]", e)

    # ── Cleanup ────────────────────────────────────────────────
    # This runs whether the connection ended normally or with an error
    finally:
        # Remove the device from the active clients dictionary
        with lock:
            if device_id and device_id in clients:
                del clients[device_id]

        conn.close()   # Close the socket

        if device_id:
            print(f"[DISCONNECTED] {device_id}")


# ============================================================
# send_command() — Terminal interface to send commands manually
# ============================================================
# Runs in a background thread. Lets the server operator type
# commands directly into the terminal without using the web UI.
# Useful for testing and debugging.
# ============================================================
def send_command():

    global pause_print

    while True:

        # Get a snapshot of currently connected devices
        with lock:
            device_list = list(clients.keys())

        # If no devices are connected, wait and check again
        if not device_list:
            time.sleep(2)
            continue

        # Pause any background prints so the terminal prompt is clean
        pause_print = True

        print("\nConnected devices:", device_list)

        choice = input("Send command? (y/n): ")

        if choice.lower() != "y":
            pause_print = False
            continue

        device = input("Device ID: ")
        command = input("Command (LED_ON / LED_OFF): ")

        with lock:
            # Check the device is still connected
            if device not in clients:
                print("Device not found")
                pause_print = False
                continue

            # Build and send the command message
            msg = {
                "type": "COMMAND",
                "command": command,
                "sent_time": time.time()   # Timestamp for latency measurement
            }

            try:
                clients[device].send(json.dumps(msg).encode())
                print("[COMMAND SENT]")
            except Exception as e:
                print("[SEND ERROR]", e)

        pause_print = False


# ============================================================
# start_server() — Sets up TLS and starts accepting connections
# ============================================================
def start_server():

    # ── SSL Context Setup ──────────────────────────────────────
    # PROTOCOL_TLS_SERVER = use the best available TLS version
    context = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)

    # Load the server's certificate and private key
    # server.crt = proves our identity to clients
    # server.key = used to decrypt data encrypted with our certificate
    context.load_cert_chain(certfile=CERT_FILE, keyfile=KEY_FILE)

    # ── Raw TCP Socket Setup ───────────────────────────────────
    raw_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    # AF_INET = IPv4, SOCK_STREAM = TCP (reliable, ordered)

    # SO_REUSEADDR = allows restarting the server immediately after stopping
    # without waiting for the OS to release the port
    raw_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)

    # Bind to all interfaces on port 5000
    raw_socket.bind((HOST, PORT))

    # Start listening — accept up to 5 queued connections
    raw_socket.listen(5)

    print(f"[SERVER STARTED] TLS/SSL server running on port {PORT}")

    # Start the terminal command interface in a background daemon thread
    # daemon=True means this thread will automatically stop when main program exits
    threading.Thread(target=send_command, daemon=True).start()

    # ── Main Accept Loop ───────────────────────────────────────
    # Wait for incoming connections forever
    while True:

        # Accept a raw (unencrypted) TCP connection
        client_socket, addr = raw_socket.accept()

        # Wrap the raw socket with TLS encryption
        # This performs the TLS handshake — agreeing on encryption keys
        try:
            secure_conn = context.wrap_socket(client_socket, server_side=True)
        except (ssl.SSLError, ConnectionAbortedError, ConnectionResetError, OSError) as e:
            # Handshake failed — client may not be using SSL
            print(f"[TLS HANDSHAKE FAILED] {addr}: {e}")
            client_socket.close()
            continue   # Skip this connection and wait for the next one

        # Spawn a new thread to handle this client
        # args=(secure_conn, addr) passes the encrypted socket and address
        threading.Thread(
            target=handle_client,
            args=(secure_conn, addr),
            daemon=True
        ).start()


# ── Entry Point ────────────────────────────────────────────
# Only runs when this file is executed directly
# (not when imported as a module)
if __name__ == "__main__":
    start_server()
